dist: xenial

language: python

python:
 - "3.6"

addons:
  postgresql: "9.5"
  apt:
    packages:
      - gdal-bin
      - libgdal-dev
      - python3-psycopg2
      - postgresql-9.5-postgis-2.4

install:
 - CPLUS_INCLUDE_PATH=/usr/include/gdal C_INCLUDE_PATH=/usr/include/gdal pip install 'gdal<1.11'
 - pip install black flake8 isort codecov coverage
 - pip install psycopg2==2.7.4
 - pip install -r requirements.txt
 - pip install -r requirements-dev.txt
 - git clone https://github.com/openmeteo/enhydris.git ../enhydris
 - pip install -r ../enhydris/requirements.txt
 - pip install -r ../enhydris/requirements-dev.txt

before_script:
 - psql -U postgres -c "create extension postgis"
 - psql -U postgres -c "create database openmeteo"
 - cp .travis-settings.py ../enhydris/enhydris_project/settings/local.py
 - cd ../enhydris
 - ln -s ../enhydris-synoptic/enhydris_synoptic .
 - mkdir /tmp/enhydris-synoptic-root

env:
 - SELENIUM_BROWSER=PhantomJS

script:
 - python manage.py makemigrations --check
 - black --check enhydris_synoptic
 - flake8 --max-line-length=88 enhydris_synoptic
 - ( cd ../enhydris-synoptic && isort --recursive --check-only --diff enhydris_synoptic )
 - coverage run --include="./enhydris_synoptic/*" --omit="*/tests/*","*/tests.py","*/migrations/*" ./manage.py test -v2 enhydris_synoptic

after_success:
 - codecov
